import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
import React from "react";
import { ThemeProvider, createTheme } from "@mui/material";
import customTheme from "@/theme";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <AuthProvider>
                <ThemeProvider theme={customTheme}>
                    <body className={inter.className}>
                    <Toaster position="top-right"/>
                        {children}
                    </body>
                </ThemeProvider>
            </AuthProvider>
        </html>
    );
}
